### ISSUE TITLE
[PE-D] Broken hyperlinks in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W12-4/tp#169] opened 2022-04-01 16:26 UTC
The hyperlinks to the *contacts tutorial* and the *meetings tutorial* in the **Getting Started with Reache** section in the UG are broken.

![image.png](https://raw.githubusercontent.com/petermonky/ped/main/files/a0770bee-4bc3-43d9-bd83-bf370de84b05.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: petermonky/ped#3

**Comment by muraddurrani** [comment] 2022-04-03 09:21
Duplicate of #166

**Closed by muraddurrani** 2022-04-03 09:21 UTC
